import { HabitData } from "../types/type";

export const defaultHabits: HabitData[] = [
  {
    user_id: '',
    habit_name: 'Study',
    habit_img: 'https://habitstack.s3.eu-north-1.amazonaws.com/read.png',
    habit_target_time: 8,
    habit_target_type: 'hours',
    habit_accumulating_time: 0,
    habit_progress: 0,
    is_checked: false,
    checked_dates: [],
    hours_accumulated_period: [],
    goal_reached: false,
  },
  {
    user_id: '',
    habit_name: 'Work out',
    habit_img: 'https://habitstack.s3.eu-north-1.amazonaws.com/gym.png',
    habit_target_time: 30,
    habit_target_type: 'days',
    habit_accumulating_time: 0,
    habit_progress: 0,
    is_checked: false,
    checked_dates: [],
    hours_accumulated_period: [],
    goal_reached: false,
  },
  {
    user_id: '',
    habit_name: 'Yoga',
    habit_img: 'https://habitstack.s3.eu-north-1.amazonaws.com/yoga.png',
    habit_target_time: 30,
    habit_target_type: 'days',
    habit_accumulating_time: 0,
    habit_progress: 0,
    is_checked: false,
    checked_dates: [],
    hours_accumulated_period: [],
    goal_reached: false,
  },
  {
    user_id: '',
    habit_name: 'Sleep before 11pm',
    habit_img: 'https://habitstack.s3.eu-north-1.amazonaws.com/bed.png',
    habit_target_time: 30,
    habit_target_type: 'days',
    habit_accumulating_time: 0,
    habit_progress: 0,
    is_checked: false,
    checked_dates: [],
    hours_accumulated_period: [],
    goal_reached: false,
  },
  {
    user_id: '',
    habit_name: 'Vitamin',
    habit_img: 'https://habitstack.s3.eu-north-1.amazonaws.com/vitamin.png',
    habit_target_time: 100,
    habit_target_type: 'days',
    habit_accumulating_time: 0,
    habit_progress: 0,
    is_checked: false,
    checked_dates: [],
    hours_accumulated_period: [],
    goal_reached: false,
  },
];